services:
  svelte:
    container_name: svelte
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - svelte-postgres-db:/data/postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: svelteuser
      POSTGRES_PASSWORD: svelteuser
      POSTGRES_DB: svelte

volumes:
  svelte-postgres-db:
